version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "alembic upgrade head &&
      uvicorn quan.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      ENVIRONMENT: development
      DEBUG: "true"
      DATABASE_URL: sqlite:////app/data/quan.db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
