"""
Optimization module for Collection Intelligence platform.

Contains parameter tuning engines for:
- Negotiation strategies
- Settlement offers
- Payment plans
- Channel optimization with multi-armed bandit selection
- Lifecycle ROI optimization with full account economics
- Cross-validation ensemble optimization with confidence intervals
- Unit economics optimization with Dead Zone resurrection analysis
- System performance optimization with timing, pricing, and simulation
"""

from .negotiation_tuner import (
    NegotiationSimulator,
    NegotiationStrategy,
    NegotiationApproach,
    DebtorSegment,
    GameTheoryEngine,
    NegotiationAnalytics,
    NEGOTIATION_STRATEGIES,
    SETTLEMENT_AUTHORITY,
    PAYMENT_PLAN_TIERS,
    run_negotiation_tuner,
)

from .channel_optimizer import (
    ChannelOptimizationEngine,
    MultiArmedBandit,
    ChannelEffectivenessModel,
    Channel,
    DebtType,
    BalanceTier,
    DPDBucket,
    DebtorDemographics,
    ChannelPerformance,
    SegmentKey,
    ChannelSequence,
    CHANNEL_COSTS,
    run_channel_optimization,
)

from .lifecycle_roi import (
    LifecycleROIOptimizer,
    LifecycleCostModel,
    AcquisitionCosts,
    ProcessingCosts,
    ChannelCosts,
    ComplianceCosts,
    ReEngagementCosts,
    AccountLifecycle,
    SegmentMetrics,
    PortfolioOptimization,
    DebtTypeSegment,
    SEGMENT_PROFILES,
    BALANCE_TIER_BOUNDS,
    run_lifecycle_optimization,
)

from .ensemble_optimizer import (
    EnsembleOptimizer,
    CrossValidationEngine,
    EnsembleModel,
    OverfittingDetector,
    BootstrapCI,
    OptimizerType,
    AccountData,
    FoldMetrics,
    CVResults,
    ConfidenceInterval,
    EnsembleWeight,
    OverfitAssessment,
    EnsemblePrediction,
    RobustRecommendation,
    CVAccountGenerator,
    OptimizerSimulator,
    CV_FOLDS,
    ACCOUNTS_PER_FOLD,
    BOOTSTRAP_SAMPLES,
    BOOTSTRAP_CONFIDENCE_LEVEL,
    run_ensemble_optimization,
)

from .unit_economics import (
    UnitEconomicsOptimizer,
    CostModel,
    RevenueModel,
    BreakEvenAnalyzer,
    ChannelOptimizer,
    PortfolioEconomicsEngine,
    SensitivityAnalyzer,
    ComparisonEngine,
    FixedCosts,
    VariableCosts,
    RecoveryParameters,
    UnitEconomicsResult,
    ChannelOptimization,
    PortfolioEconomics,
    MonteCarloResult,
    BalanceTier,
    Channel,
    PortfolioScale,
    Scenario,
    TRADITIONAL_CTC,
    QUAN_CTC,
    DEAD_ZONE_MARKET_SIZE,
    run_unit_economics_demo,
)

from .performance import (
    SystemPerformanceOptimizer,
    ContactTimingOptimizer,
    ChannelSequencingOptimizer,
    MessageOptimizationEngine,
    SettlementPricingOptimizer,
    ResourceAllocationOptimizer,
    PortfolioOptimizer,
    FeedbackLoopEngine,
    BenchmarkTracker,
    SimulationEngine,
    ConsumerSegment,
    PayFrequency,
    MessageTone,
    RiskTier,
    TestStatus,
    ContactWindow,
    TimingRecommendation,
    ChannelSequence as PerformanceChannelSequence,
    ChannelWaterfallResult,
    ABTestVariant,
    ABTest,
    SettlementOffer,
    WillingnessToPayModel,
    ResourceAllocation,
    AccountPriority,
    PortfolioOptimization as PerformancePortfolioOptimization,
    FeedbackSignal,
    StrategyEffectiveness,
    BenchmarkComparison,
    SimulationScenario,
    SimulationResult,
    SEGMENT_OPTIMAL_HOURS,
    SEGMENT_OPTIMAL_DAYS,
    INDUSTRY_BENCHMARKS,
    run_performance_optimization_demo,
)

__all__ = [
    # Negotiation tuner
    "NegotiationSimulator",
    "NegotiationStrategy",
    "NegotiationApproach",
    "DebtorSegment",
    "GameTheoryEngine",
    "NegotiationAnalytics",
    "NEGOTIATION_STRATEGIES",
    "SETTLEMENT_AUTHORITY",
    "PAYMENT_PLAN_TIERS",
    "run_negotiation_tuner",
    # Channel optimizer
    "ChannelOptimizationEngine",
    "MultiArmedBandit",
    "ChannelEffectivenessModel",
    "Channel",
    "DebtType",
    "BalanceTier",
    "DPDBucket",
    "DebtorDemographics",
    "ChannelPerformance",
    "SegmentKey",
    "ChannelSequence",
    "CHANNEL_COSTS",
    "run_channel_optimization",
    # Lifecycle ROI optimizer
    "LifecycleROIOptimizer",
    "LifecycleCostModel",
    "AcquisitionCosts",
    "ProcessingCosts",
    "ChannelCosts",
    "ComplianceCosts",
    "ReEngagementCosts",
    "AccountLifecycle",
    "SegmentMetrics",
    "PortfolioOptimization",
    "DebtTypeSegment",
    "SEGMENT_PROFILES",
    "BALANCE_TIER_BOUNDS",
    "run_lifecycle_optimization",
    # Ensemble optimizer
    "EnsembleOptimizer",
    "CrossValidationEngine",
    "EnsembleModel",
    "OverfittingDetector",
    "BootstrapCI",
    "OptimizerType",
    "AccountData",
    "FoldMetrics",
    "CVResults",
    "ConfidenceInterval",
    "EnsembleWeight",
    "OverfitAssessment",
    "EnsemblePrediction",
    "RobustRecommendation",
    "CVAccountGenerator",
    "OptimizerSimulator",
    "CV_FOLDS",
    "ACCOUNTS_PER_FOLD",
    "BOOTSTRAP_SAMPLES",
    "BOOTSTRAP_CONFIDENCE_LEVEL",
    "run_ensemble_optimization",
    # Unit economics optimizer
    "UnitEconomicsOptimizer",
    "CostModel",
    "RevenueModel",
    "BreakEvenAnalyzer",
    "ChannelOptimizer",
    "PortfolioEconomicsEngine",
    "SensitivityAnalyzer",
    "ComparisonEngine",
    "FixedCosts",
    "VariableCosts",
    "RecoveryParameters",
    "UnitEconomicsResult",
    "ChannelOptimization",
    "PortfolioEconomics",
    "MonteCarloResult",
    "BalanceTier",
    "Channel",
    "PortfolioScale",
    "Scenario",
    "TRADITIONAL_CTC",
    "QUAN_CTC",
    "DEAD_ZONE_MARKET_SIZE",
    "run_unit_economics_demo",
    # Performance optimizer
    "SystemPerformanceOptimizer",
    "ContactTimingOptimizer",
    "ChannelSequencingOptimizer",
    "MessageOptimizationEngine",
    "SettlementPricingOptimizer",
    "ResourceAllocationOptimizer",
    "PortfolioOptimizer",
    "FeedbackLoopEngine",
    "BenchmarkTracker",
    "SimulationEngine",
    "ConsumerSegment",
    "PayFrequency",
    "MessageTone",
    "RiskTier",
    "TestStatus",
    "ContactWindow",
    "TimingRecommendation",
    "PerformanceChannelSequence",
    "ChannelWaterfallResult",
    "ABTestVariant",
    "ABTest",
    "SettlementOffer",
    "WillingnessToPayModel",
    "ResourceAllocation",
    "AccountPriority",
    "PerformancePortfolioOptimization",
    "FeedbackSignal",
    "StrategyEffectiveness",
    "BenchmarkComparison",
    "SimulationScenario",
    "SimulationResult",
    "SEGMENT_OPTIMAL_HOURS",
    "SEGMENT_OPTIMAL_DAYS",
    "INDUSTRY_BENCHMARKS",
    "run_performance_optimization_demo",
]
